CREATE TABLE users (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(500) NOT NULL,
  email varchar(500) NOT NULL,
  bio varchar(500),
  image varchar(500),
  password_hash varchar(500) NOT NULL
);

--gopg:split

CREATE TABLE articles (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug varchar(500),
  title varchar(500) NOT NULL,
  description varchar(500) NOT NULL,
  body varchar NOT NULL,
  author_id int8,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE TABLE article_tags (
  article_id int8,
  tag varchar(500)
);

CREATE UNIQUE INDEX article_tags_article_id_tag_idx
ON article_tags (article_id, tag);

CREATE TABLE favorite_articles (
  user_id int8,
  article_id int8
);

CREATE UNIQUE INDEX favorite_articles_user_id_article_id_idx
ON favorite_articles (user_id, article_id);