CREATE TABLE users (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(500),
  email varchar(500) NOT NULL,
  bio varchar(500),
--   image varchar(500),
  password_hash varchar(500) NOT NULL,
  email_confirmed boolean
);

--gopg:split
